services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TaskDb123"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
    driver: local

